volumes:
  mysql-db:
    driver: local
networks:
  app_network:
    driver: bridge

services:
  db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=snippetbox
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=web
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: snippetbox_sql
    command: --default-authentication-plugin=mysql_native_password
