// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/forms/form.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./pkg/forms/mocks/mock_form.go -source ./pkg/forms/form.go
//

// Package mocks is a generated GoMock package.
package mocks
